Fix errors on run.py when running on macOS ARM m2
These were the errors:

/python3.11/site-packages/torchaudio/_backend/utils.py", line 346, in save
    return backend.save(
           ^^^^^^^^^^^^^
  File "python3.11/site-packages/torchaudio/_backend/soundfile.py", line 42, in save
    raise ValueError("soundfile backend does not support argument `compression`.")
ValueError: soundfile backend does not support argument `compression`.

    return self.numpy()
           ^^^^^^^^^^^^
RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.